# Stage 1: Build
FROM golang:1.27.1@sha256:f44f6e88636cfb311f9ebace870ded69d943f227bb3cb27d32ffd84ea18c43ea AS builder
RUN apt-get update && apt-get install -y gcc libc-dev
WORKDIR /app
COPY cmd/nano-init/go.mod cmd/nano-init/go.sum ./
RUN go mod download
COPY cmd/nano-init/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -ldflags="-s -w" -o nano-init .

# Stage 2: Final
FROM gcr.io/distroless/base:nonroot@sha256:0896741ba5bafd3ac87ea025a5f578952f2d238ddc3614cb368acc983a687aa2
COPY --from=builder --chown=nonroot:nonroot /app/nano-init /
USER nonroot:nonroot
ENTRYPOINT ["/nano-init"]
